name: Trigger Real-time Weather Fetch

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟
    - cron: '0 6,12,18 * * *'   # 每天6:00、12:00、18:00
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Check time window
        id: time_check
        run: |
          CURRENT_HOUR=$(date +%-H)
          if [ $CURRENT_HOUR -ge 5 ] && [ $CURRENT_HOUR -lt 24 ]; then
            echo "valid_time=true" >> "$GITHUB_OUTPUT"
          else
            echo "valid_time=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Trigger Real-time Weather Fetch
        if: steps.time_check.outputs.valid_time == 'true'
        run: |
          curl -X POST https://nexus8023.pythonanywhere.com/api/weather/fetch_weather
